package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'ProductionDemo_HttpsGithubComEpaloshForeflightProductionDemoGitRefsHeadsMain'
in the project with id = 'ProductionDemo', and delete the patch script.
*/
create(RelativeId("ProductionDemo"), GitVcsRoot({
    id("ProductionDemo_HttpsGithubComEpaloshForeflightProductionDemoGitRefsHeadsMain")
    name = "https://github.com/epalosh-foreflight/ProductionDemo.git#refs/heads/main"
    url = "https://github.com/epalosh-foreflight/ProductionDemo.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "epalosh-foreflight"
        password = "credentialsJSON:8c16e2aa-45e2-4574-a391-0e0a67795196"
    }
}))

