package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'SandboxDemo2_HttpsGithubComEpaloshForeflightProductionDemoRefsHeadsSandbox'
in the project with id = 'SandboxDemo2', and delete the patch script.
*/
create(RelativeId("SandboxDemo2"), GitVcsRoot({
    id("SandboxDemo2_HttpsGithubComEpaloshForeflightProductionDemoRefsHeadsSandbox")
    name = "https://github.com/epalosh-foreflight/ProductionDemo#refs/heads/sandbox"
    url = "https://github.com/epalosh-foreflight/ProductionDemo"
    branch = "refs/heads/sandbox"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "epalosh-foreflight"
        password = "credentialsJSON:8c16e2aa-45e2-4574-a391-0e0a67795196"
    }
}))

